In [1]:
from numpy.random import seed
seed(1)
# Dependencies
import numpy as np
import pandas as pd
import tensorflow
tensorflow.keras.__version__

'2.2.4-tf'

In [2]:
df = pd.read_csv('fc3.csv')
df.head()

Date  Year  DOY  Solar  Wind_speed  Wind_dir  gust  temp    rh  \
0  10/1/2001  2001  274  383.0        2.00     120.0  19.0  47.8  50.0   
1  10/2/2001  2001  275  478.0        3.83     124.0  27.0  49.0  40.0   
2  10/3/2001  2001  276  482.0        3.35      60.0  22.0  47.3  37.0   
3  10/4/2001  2001  277  483.0        5.12     333.0  27.0  47.2  32.0   
4  10/5/2001  2001  278  482.0        3.46       3.0  24.0  39.2  38.0   

   precip  ...  Webber Springs  Webster Flat  Whiskey Ck  Whiskey Park  \
0     0.0  ...             0.0           0.0         0.0           0.0   
1     0.0  ...             0.0           0.0         0.1           0.0   
2     0.0  ...             0.0           0.0         0.0           0.0   
3     0.0  ...             0.0           0.0         0.0           0.0   
4     0.0  ...             0.1           0.0         0.0           0.0   

   White Elephant  White Mill  Widtsoe #3  Willow Creek  Willow Creek Pass  \
0             0.0         0.0         0.0           0.0                0.1   
1             0.0         0.0         0.0           0.0                0.0   
2             0.0         0.0         0.0           0.0                0.0   
3             0.0         0.0         0.0           0.0                0.0   
4             0.0         0.0         0.0           0.0                0.0   

   Windy Peak  
0         0.1  
1         0.0  
2         0.0  
3         0.3  
4         0.3  

[5 rows x 218 columns]

In [3]:
target =df['binary_3']
taget_names = ['yes','no']


In [4]:

data = df.drop(['binary_3','Date'], axis = 1 )
feature_names = data.columns
data.fillna(df.mean(), inplace=True)

In [5]:
data

Year  DOY  Solar  Wind_speed  Wind_dir  gust  temp    rh  precip  \
0     2001  274  383.0        2.00     120.0  19.0  47.8  50.0    0.00   
1     2001  275  478.0        3.83     124.0  27.0  49.0  40.0    0.00   
2     2001  276  482.0        3.35      60.0  22.0  47.3  37.0    0.00   
3     2001  277  483.0        5.12     333.0  27.0  47.2  32.0    0.00   
4     2001  278  482.0        3.46       3.0  24.0  39.2  38.0    0.00   
...    ...  ...    ...         ...       ...   ...   ...   ...     ...   
7088  2021   57  431.0        7.21     287.0  53.0  19.8  42.0    0.00   
7089  2021   58  210.0        4.12     346.0  24.0  11.8  70.0    0.00   
7090  2021   59  493.0        3.08      59.0  15.0   5.8  56.0    0.01   
7091  2021   60  510.0        2.67     148.0  12.0  16.4  54.0    0.00   
7092  2021   61  518.0        3.00      54.0  14.0  25.1  47.0    0.00   

      Agua Canyon  ...  Webber Springs  Webster Flat  Whiskey Ck  \
0             0.0  ...             0.0           0.0         0.0   
1             0.0  ...             0.0           0.0         0.1   
2             0.0  ...             0.0           0.0         0.0   
3             0.0  ...             0.0           0.0         0.0   
4             0.1  ...             0.1           0.0         0.0   
...           ...  ...             ...           ...         ...   
7088          0.0  ...             0.5           0.0         0.0   
7089          0.0  ...             0.2           0.0         0.0   
7090          0.0  ...             0.0           0.0         0.2   
7091          0.0  ...             0.1           0.3         0.3   
7092          0.0  ...             0.1           0.1         0.0   

      Whiskey Park  White Elephant  White Mill  Widtsoe #3  Willow Creek  \
0              0.0             0.0         0.0         0.0           0.0   
1              0.0             0.0         0.0         0.0           0.0   
2              0.0             0.0         0.0         0.0           0.0   
3              0.0             0.0         0.0         0.0           0.0   
4              0.0             0.0         0.0         0.0           0.0   
...            ...             ...         ...         ...           ...   
7088           0.6             0.7         0.2         0.0           0.6   
7089           0.3             0.1         0.0         0.0           0.5   
7090           0.0             0.0         0.0         0.0           0.1   
7091           0.1             0.0         0.2         0.1           0.1   
7092           0.1             0.0         0.0         0.0           0.1   

      Willow Creek Pass  Windy Peak  
0                   0.1         0.1  
1                   0.0         0.0  
2                   0.0         0.0  
3                   0.0         0.3  
4                   0.0         0.3  
...                 ...         ...  
7088                0.0         0.0  
7089                0.3         0.1  
7090                0.0         0.0  
7091                0.1         0.2  
7092                0.1         0.1  

[7093 rows x 216 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [7]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.5558060879368658

In [8]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.6358511837655016

In [9]:
tree_predict = clf.predict(data)

In [10]:
tree_predict

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
forest_predict= rf.predict(data)

In [12]:
forest_predict

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
forest_prob= rf.predict_proba(data)

In [14]:
forest_prob

array([[0.86 , 0.14 ],
       [0.28 , 0.72 ],
       [0.885, 0.115],
       ...,
       [0.875, 0.125],
       [0.81 , 0.19 ],
       [0.795, 0.205]])